### ISSUE TITLE
Role of ROpenSci in the package

### ISSUE THREAD

**Issue by beatrizmilz** [hsvab/odbr#11]
Hi @yabellini! @hsvab and I are in a meeting now, and one of the things we are discussing is the DESCRIPTION file.

One question is: how do we acknowledge ROpenSci (and the champions program) in the package?

https://r-pkgs.org/description.html#sec-description-authors-at-r 
As a funder? What do you recommend?

**Comment by yabellini** [comment]
Hi, thank you for this question.  We creates a tag that you can add to the readme.  Let me ask how we should use it.
