### ISSUE TITLE
Function read_dictionary() currently does not return dictionary data.frame

### ISSUE THREAD

**Issue by rafapereirabr** [hsvab/odbr#13]
https://github.com/hsvab/odbr/blob/67435807850917b1d958e9c5d728039baa862b42/R/read_dictionary.R#L30C3-L30C24

The function `read_dictionary()` currently returns the url address of the dictionary. The file still needs to be downloaded and read. Something along these lines:

```
# download dictionary
dic_file <- download_piggyback(filename_to_download) 

# read dictionary
dic <- data.table::fread(filename_to_download)

return(dic)
```

**Comment by hsvab** [comment]
Not all the files are up to date, but the function should be working properly now. Could you try again @rafapereirabr?

**Comment by rafapereirabr** [comment]
I just tested the function and it's working great! thanks !
