### ISSUE TITLE
Documentar data assets

### ISSUE THREAD

**Issue by diraol** [hsvab/odbr#20]
É necessário documentar os "data assets" (metadata, dicionários, etc).

Ref: https://r-pkgs.org/data.html#sec-documenting-data

**Comment by beatrizmilz** [comment]
Eu enviei uma v1 aqui, mas seria bom revisar se tudo que eu escrevi tá certo: https://github.com/hsvab/odbr/blob/main/R/data.R

**Comment by beatrizmilz** [comment]
ah e precisa rodar o `devtools::document()` ou o botão no build -> document, e commitar os arquivos. Assim vai aparecer lá no site :)
