### ISSUE TITLE
Criar logo com Hex sticker \o/

### ISSUE THREAD

**Issue by rafapereirabr** [hsvab/odbr#25]
Essa é a parte mais divertida :)

**Comment by hsvab** [comment]
Tenho um esboço e um amigo topou fazer a arte pra mim - que acham @beatrizmilz @diraol e @rafapereirabr ?


![odbr-logo](https://github.com/hsvab/odbr/assets/2137923/9dda7fda-60ec-492a-8991-f311d7ecede6)

**Comment by hsvab** [comment]
Outra duvida é: como dou os créditos da imagem pra ele

**Comment by diraol** [comment]
Adorei!

E acho que você pode colocar os créditos no README.md do projeto.

**Comment by rafapereirabr** [comment]
eu gosto muito da ideia! É tão simples (clean) que daria para criar dentro do R :)  Mas vamos ver o que seu amigo propõe de ajustes de cores, fonte, etc etc.

Concordo com @diraol, dar os creditos no README.md seria o caminho.

**Comment by hsvab** [comment]
![ODBR logo v4 hexagonal](https://github.com/hsvab/odbr/assets/2137923/50c8458f-0505-41fd-9013-da22378dc481)
