### ISSUE TITLE
Change in function descriptions

### ISSUE THREAD

**Issue by hsvab** [hsvab/odbr#30]
#1 feedback from CRAN

Please do not start the description with "Functions for", "This package", package name, title or similar.

The Description field is intended to be a (one paragraph) description of what the package does and why it may be useful. Please add more details about the package functionality and implemented methods in your Description text.

**Comment by hsvab** [comment]
@beatrizmilz I've already worked on that issue, but you could you please take a look at the functions and etc documentation and point out if there is anything else to change?

**Comment by beatrizmilz** [comment]
https://github.com/hsvab/odbr/blob/95abdd6cb6e4be292ce991e2356fac0fdd260dfd/DESCRIPTION#L12

It seems to be well explained! I didn't know about this CRAN rule.
