### ISSUE TITLE
Review references

### ISSUE THREAD

**Issue by hsvab** [hsvab/odbr#31]
#2 feedback from CRAN

If there are references describing the methods in your package, please add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: <https:...>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for auto-linking.
(If you want to add a title as well please put it in quotes: "Title")

**Comment by hsvab** [comment]
@rafapereirabr, could you help me with this?

**Comment by rafapereirabr** [comment]
Sure! I'm currently on a trip, way from the office and computer. I'll have a look at this as soon as I get back , by Friday Rafael H M Pereira
-------- Original message --------From: Haydee Svab ***@***.***> Date: 10/23/23  06:33  (GMT-03:00) To: hsvab/odbr ***@***.***> Cc: Rafael H M Pereira ***@***.***>, Mention ***@***.***> Subject: Re: [hsvab/odbr] Review references (Issue #31) 
@rafapereirabr, could you help me with this?

**Comment by rafapereirabr** [comment]
Hi @hsvab . As far as I understand, this is a data package, and so the package is not built on top any particular study or method. So there is no need to mention this in the `DESCRIPTION`. Having said that, I had  a look at the `DESCRIPTION` file and I would suggest a few edits. See suggested text below. Feel free to incorporated only the suggestions / edits you see fit. 

> Description: Download data from Brazil's Origin Destination Surveys. The package covers both data from household travel surveys, dictionaries of variables, and the spatial geometries of surveys conducted in different years and across various urban areas in Brazil. For some cities, the package will include enhanced versions of the data sets with variables "harmonized" across different years.
