### ISSUE TITLE
Padronizar nomes de arquivos para expansao do pacote

### ISSUE THREAD

**Issue by rafapereirabr** [hsvab/odbr#4]
Opa! seria uma boa padronizar os nomes do arquivos de maneira a facilitar a expansão do pacote para incluir as ODs de novas cidades. A sugestão é estabelecer um padrão geral para todas cidades. Partindo dos nomes que já estão sendo usados, minha sugestão seria a seguinte:

[tipo de dado] _ [ano] _ [cidade polo] _ [status de harmonizado] . [extensao]

Exemplo:
- zonas_1977_sao_paulo.gpkg
- municipios_1977_sao_paulo.gpkg
- od_1977_sao_paulo_harmonized.csv
- od_1977_sao_paulo_notharmonized.gpkg

Esse tipo de padronização facilita muito a navegação dos arquivos e até a criação de funções para filtrar / selecionar arquivos especificos.

ps. para os arquivos que já estão online no release,  é possível renomear eles online mesmo, sem ter que fazer upload novamente

**Comment by hsvab** [comment]
Obrigada pela sugestão!
Uniformizando por aqui com uma pequena diferença:
[tipo de dado] _ [cidade polo] _ [ano] _ [status de harmonizado] . [extensao]
