### ISSUE TITLE
Atualizar autoria

### ISSUE THREAD

**Issue by beatrizmilz** [hsvab/odbr#9]
https://github.com/hsvab/odbr/blob/1dbbb7bc7824291b98076b646696cd8335539b39/DESCRIPTION#L4-L6

Referência: https://r-pkgs.org/description.html#sec-description-authors-at-r

```
One or more three letter codes specifying the role. These are the most important roles to know about:

    cre: the creator or maintainer, the person you should bother if you have problems. Despite being short for “creator”, this is the correct role to use for the current maintainer, even if they are not the initial creator of the package.

    aut: authors, those who have made significant contributions to the package.

    ctb: contributors, those who have made smaller contributions, like patches.

    cph: copyright holder. This is used to list additional copyright holders who are not authors, typically companies, like an employer of one or more of the authors.

    fnd: funder, the people or organizations that have provided financial support for the development of the package.
```

**Comment by beatrizmilz** [comment]
Creator: Haydee
fnd: perguntar para a Yani!
ctb: Rafa, Diego 
aut: Haydee, Bia

**Comment by beatrizmilz** [comment]
Perguntar para o Rafa sobre a contribuição dele!

**Comment by rafapereirabr** [comment]
Opa ! Além das coversas que temos tido sobre arquitura do pacote etc, eu tamém topo contribuir com:

- código para funções do pacote
- revisão de vignette, 
- codigo para gihub actions (package down e cmd-checks, code coverage) 
- contribuir com bases de dados de mais cidades do Brasil 
  - Campinas 2003
  - DF 2000 e 2012
  - Recife 2018
  - Rio 2003 e 2012

Entendo que a liderança do pacote é da @hsvab , então fico a disposição para o que vocês precisarem

**Comment by hsvab** [comment]
@rafapereirabr e @diraol Adicionados como autores ;-)
